### ISSUE TITLE
The orange effect is wrong

### ISSUE THREAD

**Issue by fromwhite** [Ctrlmonster/r3f-effekseer#2]
First click on the orange sphere geometry, and then click on the hotlink, Laser02 has replaced the original Laser01.

This is really a cool thing, I tried to create some interactive scenes with it.Looking forward to NPM pkg.

**Comment by Ctrlmonster** [comment]
Sounds like a bug, thanks for raising this, I'll investigate.
Glad to hear it! Hoping to get the lib out soon🙌
