### ISSUE TITLE
targetPosition invalid

### ISSUE THREAD

**Issue by 273032860** [Ctrlmonster/r3f-effekseer#3]
Laser01.efk    
my code
<Effekt ref={laserRef}
              debug
              name={"Laser01"}
              src={laser1Url}
              dispose={null}
              position={[-2, 0, 0]}
              scale={[0.5, 0.5, 0.5]}
              speed={1}
              targetPosition={[0.0,2.0,0.0]}
            />

**Comment by Ctrlmonster** [comment]
Afaik `targetPosition` is a Effekseer internal property (internally called `targetLocation`) that not every effect necessary has. I think this is likely a field that needs to be set when creating an effect in the effekseer editor. I'll have to make this more clear in the docs, thanks for bringing it up.
